StartupEvents.registry("block",event => {
    
    event.create("cmc:computing_casing")
    .textureAll('cmc:block/computing_top')
    .soundType(SoundType.METAL)
    .hardness(5)
    .resistance(5)
    .requiresTool(true)
    .tagBlock("create:wrench_pickup")
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:mineable/pickaxe')

    event.create("cmc:sky_stone_casing")
    .textureAll('cmc:block/smart')
    .soundType(SoundType.METAL)
    .hardness(5)
    .resistance(5)
    .requiresTool(true)
    .tagBlock("create:wrench_pickup")
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:mineable/pickaxe')

event.create("cmc:creative_fiuld_tank","basic")
    .textureSide("down","cmc:block/creative_fiuld_tank_bottom")
    .textureSide("up","cmc:block/creative_fiuld_tank_top")
    .textureSide("north","cmc:block/creative_fiuld_tank_side")
    .textureSide("south","cmc:block/creative_fiuld_tank_side")
    .textureSide("east","cmc:block/creative_fiuld_tank_side")
    .textureSide("west","cmc:block/creative_fiuld_tank_side")
    .hardness(5)
    .requiresTool(true)
    .tagBlock("create:wrench_pickup")
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:mineable/pickaxe')
    .soundType(SoundType.METAL)
})